typography_spectrum: 0.6188227611128241
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.4535150290466845
  lightness: 0.8919009263627231
  saturation: 0.9281341244932264
  rhythmicContrast: 0.44916648766957223
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4561088182963431
analytics:
  google: null
  facebook: null
  twitter: null
name: Aστρικά Εξωσωματικά Ταξίδια
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Dhiravamsa
    url: 'http://www.dhiravamsa.com/'
    type: external
  - name: Vianna Stibal
    url: 'http://www.thetahealing.com'
    type: external
  - name: Pichest Boonthumme
    url: 'https://www.facebook.com/groups/172526076174229/'
    type: external
  - name: Tatsuo Suzuki
    url: 'https://en.wikipedia.org/wiki/Tatsuo_Suzuki_(martial_artist)'
    type: external
favicon: null
title: Αθηναίων Φώς
purpose: []
