name: Αθηνα
favicon: null
layout_spectrum: 0.90205
typography_spectrum: 0.2708571294788271
title: Αθηναίων Φως
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060404'
    - '#f9feff'
    - '#033254'
    - '#4d5a63'
    - '#92afc0'
  brandStrength: 0.9375
  lightness: 0.1408523479476571
  saturation: 0.6142427413724363
  rhythmicContrast: 0.75
purpose: []
