name: Αθηνα
favicon: null
layout_spectrum: 0.4589911988005042
typography_spectrum: 0.2708571294788271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2513666183222085
  lightness: 0.1408523479476571
  saturation: 0.6142427413724363
  rhythmicContrast: 0.09344747546128929
purpose: []
