typography_spectrum: 0.8106722400989383
color:
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
  brandStrength: 0.4562996798194945
  lightness: 0.29090282530523837
  saturation: 0.9363386183977127
  rhythmicContrast: 0.021096049807965755
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.34614243428222835
analytics:
  google: null
  facebook: null
  twitter: null
name: Aστρικά Εξωσωματικά Ταξίδια
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Tatsuo Suzuki
    url: 'https://en.wikipedia.org/wiki/Tatsuo_Suzuki_(martial_artist)'
    type: external
  - name: Pichest Boonthumme
    url: >-
      https://thaitravellers.wordpress.com/2009/11/04/one-week-with-pichest-boonthumme/
    type: external
  - name: Γιώργος & Μαγδαλένα
    id: cc06010a-3ec4-4d2e-864c-7e3ac9a4a543
    type: content
  - name: Boris Tichanovsky
    id: bbef3897-19de-4a72-93fd-ca8ece6bd800
    type: content
  - name: Το σεμιάριο των Αστρικών Ταξιδιών
    id: 40ddfd87-ab92-44e3-83a9-243e5020b264
    type: content
favicon: null
title: Αθηναίων Φώς
purpose: []
