typography_spectrum: 0.32421168126165867
color:
  brandColors:
    - '#0F0000'
    - '#FEFC95'
    - '#8C8493'
    - '#DA1A2F'
    - '#FCB946'
  brandStrength: 0.5052066436037421
  lightness: 0.9037387890275568
  saturation: 0.43234584387391806
  rhythmicContrast: 0.38444211473688483
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9169898070394993
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: George Christodoulou Jagaro
  email: christodoulou_george@yahoo.co.uk
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/939b40ba-f860-44c0-b7d8-52b665b45d68.jpg
name: Αθηναίων Φώς
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Ποιοί είμαστε
    id: 9bf9c145-f21e-488e-904f-19b06b1e8df9
    type: content
  - name: Επικοινωνία
    id: cc06010a-3ec4-4d2e-864c-7e3ac9a4a543
    type: content
  - name: Σεμινάριο Aστρικών Ταξιδιών
    id: 9cc72bdb-975c-4b6f-9555-e3fc6713890e
    type: content
  - name: Σεμινάριο Αποκατάστασης της Όρασης
    id: 180b9834-56e3-4325-b250-b1b5742e2748
    type: content
favicon: null
title: Κέντρο Ολιστικής Ανάπτυξης και Θεραπείας
description: Αθηναίων Φώς
purpose: []
