typography_spectrum: 0.9132345872931182
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.5927300793118775
  lightness: 0.1309689893387258
  saturation: 0.48342516110278666
  rhythmicContrast: 0.9849709884729236
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6442516832612455
analytics:
  google: null
  facebook: null
  twitter: null
name: Aστρικά Εξωσωματικά Ταξίδια
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Dhiravamsa
    url: 'http://www.dhiravamsa.com/'
    type: external
  - name: Vianna Stibal
    url: 'http://www.thetahealing.com'
    type: external
  - name: Boris Tichanovsky
    url: 'http://www.epam.eu'
    type: external
  - name: Pichest Boonthumme
    url: 'https://www.facebook.com/groups/172526076174229/'
    type: external
  - name: Tatsuo Suzuki
    url: 'https://en.wikipedia.org/wiki/Tatsuo_Suzuki_(martial_artist)'
    type: external
favicon: null
title: Αθηναίων Φώς
purpose: []
