typography_spectrum: 0.8106722400989383
color:
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
  brandStrength: 0.4562996798194945
  lightness: 0.29090282530523837
  saturation: 0.9363386183977127
  rhythmicContrast: 0.021096049807965755
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.34614243428222835
analytics:
  google: null
  facebook: null
  twitter: null
name: Aστρικά Εξωσωματικά Ταξίδια
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Boris Tichanovsky
    id: bbef3897-19de-4a72-93fd-ca8ece6bd800
    type: content
  - name: Το σεμινάρια Ἀστρικά Ταξίδια᾽
    id: 9cc72bdb-975c-4b6f-9555-e3fc6713890e
    type: content
favicon: null
title: Αθηναίων Φώς
purpose: []
