typography_spectrum: 0.2043483352754265
color:
  brandColors:
    - '#88A825'
    - '#35203B'
    - '#911146'
    - '#CF4A30'
    - '#ED8C2B'
  brandStrength: 0.3919112510047853
  lightness: 0.13471261016093194
  saturation: 0.8315856074914336
  rhythmicContrast: 0.30701378802768886
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.14133016858249903
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: George Christodoulou Jagaro
  email: christodoulou_george@yahoo.co.uk
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/939b40ba-f860-44c0-b7d8-52b665b45d68.jpg
name: Αθηναίων Φώς
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Ποιοί είμαστε
    id: 9bf9c145-f21e-488e-904f-19b06b1e8df9
    type: content
  - name: Επικοινωνία
    id: cc06010a-3ec4-4d2e-864c-7e3ac9a4a543
    type: content
  - name: Σεμινάριο Aστρικών Ταξιδιών
    id: 9cc72bdb-975c-4b6f-9555-e3fc6713890e
    type: content
  - name: Σεμινάριο Αποκατάστασης της Όρασης
    id: 180b9834-56e3-4325-b250-b1b5742e2748
    type: content
  - name: 'Σεμινάριο Ρέικι (Usui, Chakra, Kuntalini)'
    id: e7f44021-5348-443c-97b7-27ead668248c
    type: content
favicon: null
title: Κέντρο Ολιστικής Ανάπτυξης και Θεραπείας
description: Αθηναίων Φώς
purpose: []
