typography_spectrum: 0.8106722400989383
color:
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
  brandStrength: 0.4562996798194945
  lightness: 0.29090282530523837
  saturation: 0.9363386183977127
  rhythmicContrast: 0.021096049807965755
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.34614243428222835
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: George Christodoulou Jagaro
  email: christodoulou_george@yahoo.co.uk
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/939b40ba-f860-44c0-b7d8-52b665b45d68.jpg
name: Aστρικά Εξωσωματικά Ταξίδια
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Boris Tichanovsky
    id: bbef3897-19de-4a72-93fd-ca8ece6bd800
    type: content
  - name: Το σεμινάρια Ἀστρικά Ταξίδια᾽
    id: 9cc72bdb-975c-4b6f-9555-e3fc6713890e
    type: content
  - name: Επικοινωνία
    id: cc06010a-3ec4-4d2e-864c-7e3ac9a4a543
    type: content
favicon: null
title: Αθηναίων Φώς
purpose: []
